version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'adoptapet-back'
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - ./build/libs:/libs
      - ./src/main/resources/static/images:/app/src/main/resources/static/images


    restart: always
    depends_on:
      - db

    networks:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/adoptapet?createDatabaseIfNoExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING.FLYWAY.URL: jdbc:mysql://db:3306/adoptapet?createDatabaseIfNoExist=true
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 1234

    entrypoint: [ "java", "-jar", "/libs/adotapet-0.0.1-SNAPSHOT.jar" ]


  db:
    image: 'mysql'
    container_name: adoptapet-db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'adoptapet'
    ports:
      - "4022:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - db
volumes:
  mysql-data:
networks:
  db:
    driver: bridge